package main

// Code generated by go.einride.tech/mage-tools. DO NOT EDIT.

import (
	"context"
	"fmt"
	"os"
)

func main() {
	args := os.Args[1:]
	ctx := context.Background()
	_ = ctx
	if len(args) == 0 {
		fmt.Println("Targets:")
		fmt.Println("\tAll")
		fmt.Println("\tConvcoCheck")
		fmt.Println("\tFormatMarkdown")
		fmt.Println("\tFormatYAML")
		fmt.Println("\tGitVerifyNoDiff")
		fmt.Println("\tGoModTidy")
		fmt.Println("\tGoTest")
		fmt.Println("\tGolangciLint")
		fmt.Println("\tGoreview")
		fmt.Println("\tHelloWorld")
	}
}
