version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /actions/setup
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: monthly

  - package-ecosystem: pip
    directory: tools/sgmdformat
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: tools/sgcspevaluatorcli
    schedule:
      interval: monthly
