# Code generated by go.einride.tech/sage. DO NOT EDIT.
# To learn more, see .sage/sagefile.go and https://github.com/einride/sage.

.DEFAULT_GOAL := all

sagefile := .sage/bin/sagefile

.PHONY: $(sagefile)
$(sagefile):
	@cd .sage && go mod tidy && go run .

.PHONY: sage
sage:
	@git clean -fxq $(sagefile)
	@$(MAKE) $(sagefile)

.PHONY: update-sage
update-sage:
	@cd .sage && go get -d go.einride.tech/sage@latest && go mod tidy && go run .

.PHONY: clean-sage
clean-sage:
	@git clean -fdx .sage/tools .sage/bin .sage/build

.PHONY: all
all: $(sagefile)
	@$(sagefile) "Target2901124887:All"

.PHONY: convco-check
convco-check: $(sagefile)
	@$(sagefile) "Target2901124887:ConvcoCheck"

.PHONY: format-markdown
format-markdown: $(sagefile)
	@$(sagefile) "Target2901124887:FormatMarkdown"

.PHONY: format-yaml
format-yaml: $(sagefile)
	@$(sagefile) "Target2901124887:FormatYAML"

.PHONY: git-verify-no-diff
git-verify-no-diff: $(sagefile)
	@$(sagefile) "Target2901124887:GitVerifyNoDiff"

.PHONY: go-lint
go-lint: $(sagefile)
	@$(sagefile) "Target2901124887:GoLint"

.PHONY: go-mod-tidy
go-mod-tidy: $(sagefile)
	@$(sagefile) "Target2901124887:GoModTidy"

.PHONY: go-review
go-review: $(sagefile)
	@$(sagefile) "Target2901124887:GoReview"

.PHONY: go-test
go-test: $(sagefile)
	@$(sagefile) "Target2901124887:GoTest"
