# Code generated by Mage-tools. DO NOT EDIT.

.DEFAULT_GOAL := all

mage_dir := .mage
magefile := $(mage_dir)/tools/mgmake/magefile

$(magefile): $(mage_dir)/go.mod $(shell find $(mage_dir)/.. -type f -name '*.go')
	@cd $(mage_dir) && go run ../main.go gen

.PHONY: mage-clean
mage-clean:
	@git clean -fdx $(mage_dir)

.PHONY: all
all: $(magefile)
	@$(magefile) all

.PHONY: convco-check
convco-check: $(magefile)
ifndef rev
	$(error missing argument rev="...")
endif
	@$(magefile) convcoCheck $(rev)

.PHONY: format-markdown
format-markdown: $(magefile)
	@$(magefile) formatMarkdown

.PHONY: format-yaml
format-yaml: $(magefile)
	@$(magefile) formatYaml

.PHONY: git-verify-no-diff
git-verify-no-diff: $(magefile)
	@$(magefile) gitVerifyNoDiff

.PHONY: go-mod-tidy
go-mod-tidy: $(magefile)
	@$(magefile) goModTidy

.PHONY: go-test
go-test: $(magefile)
	@$(magefile) goTest

.PHONY: golangci-lint
golangci-lint: $(magefile)
	@$(magefile) golangciLint

.PHONY: goreview
goreview: $(magefile)
	@$(magefile) goreview
