name: Setup Sage
description: Setup Sage, including caching of tools and Go modules.

inputs:
  cacheKey:
    description: Custom cache key used
    required: false
    default: cachekey

  disableCache:
    description: Disable cache
    required: false
    default: false

  cache-dependency-path:
    description: Path to the go.sum file(s) to use in caching.
    required: false
    default: go.sum

  check-latest:
    description: If true, checks whether the cached go version is the latest, if not then downloads the latest. Useful when you need to use the latest version.
    required: false
    default: false


runs:
  using: composite

  steps:
    - name: Cache sage folders
      if: ${{ inputs.disableCache != 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ./.sage/tools
          ./.sage/bin
        key: ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-${{ hashFiles('./.sage/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-${{ hashFiles('./.sage/go.sum') }}
          ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-
          ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-
          ${{ runner.os }}-sage-${{ github.workflow }}-
          ${{ runner.os }}-sage-
