name: Setup Sage
description: Setup Sage, including caching of tools and Go modules.

inputs:
  cacheKey:
    description: Custom cache key used
    required: false
    default: cachekey

  disableCache:
    description: Disable cache
    required: false
    default: false

  go-version:
    description: The Go version to download (if necessary) and use. Supports semver spec and ranges.
    required: false
    default: '1.24'

  check-latest:
    description: If true, checks whether the cached go version is the latest, if not then downloads the latest. Useful when you need to use the latest version.
    required: false
    default: false

  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags.
    default: 0

  checkout-submodules:
    description: "Whether to checkout submodules: `true` to checkout submodules or `recursive` to recursively checkout submodules."
    default: ''

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Needed for conventional commit linting.
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.checkout-submodules }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: ${{ inputs.check-latest }}
        cache: false # cache is handled by separate actions/cache step, see https://github.com/actions/setup-go/issues/358

    - name: Set KOCACHE environment variable
      shell: bash
      run: echo "KOCACHE=/home/runner/.ko/cache" >> $GITHUB_ENV

    # NOTE: cache key and restore key is not the same;
    # We want to always re-use the cache created by master in all our PRs. We also want any PR which modifies go.sum to create a new cache for itself.
    # Therefore the cache key is set to use GITHUB_REF_NAME and the restore key is set to use GITHUB_BASE_REF.
    # For more details, see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
    # NOTE: you need to build on push to master and on pull request in the repos which uses this reusable workflow.
    - name: Set up cache
      if: ${{ inputs.disableCache != 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ./.sage/tools
          ./.sage/bin
          /home/runner/.cache/go-build
          /home/runner/go/pkg/mod
          /home/runner/go/bin
          /home/runner/.ko/cache
        key: ${{ runner.os }}-${{ github.ref_name }}-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.base_ref }}-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}
